version: "3"

services: 
  app:
    build:
      context: .
      dockerfile: development.Dockerfile
    ports:
     - 5000:5000
    volumes:
      - .:/usr/local/src/rigel/
      - /usr/local/src/rigel/node_modules/

  prisma:
    image: prismagraphql/prisma:1.32
    restart: always
    ports:
    - 4466:4466
    environment:
      PRISMA_CONFIG: |
        port: 4466
        databases:
          default:
            connector: postgres
            host: postgres
            port: 5432
            user: prisma
            password: prisma
            migrations: true

  postgres:
    image: postgres:10.3
    restart: always
    ports:
     - 5433:5432
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres: